export default [
  {
    traderName: "Alice",
    symbol: "BTC",
    amount: 0.5,
    price: 45000,
    tradeType: "buy",
    location: "New York, USA",
    paymentMethod: "Credit Card",
    timestamp: "2023-07-20T10:15:00Z",
  },
  {
    traderName: "Bob",
    symbol: "ETH",
    amount: 2.3,
    price: 3000,
    tradeType: "sell",
    location: "London, UK",
    paymentMethod: "Bank Transfer",
    timestamp: "2023-07-21T14:30:00Z",
  },
  {
    traderName: "Charlie",
    symbol: "XRP",
    amount: 1000,
    price: 1.5,
    tradeType: "buy",
    location: "Tokyo, Japan",
    paymentMethod: "PayPal",
    timestamp: "2023-07-22T09:45:00Z",
  },
  {
    traderName: "Eve",
    symbol: "BTC",
    amount: 0.2,
    price: 48000,
    tradeType: "sell",
    location: "Sydney, Australia",
    paymentMethod: "Cryptocurrency Wallet",
    timestamp: "2023-07-22T15:20:00Z",
  },
  {
    traderName: "Alice",
    symbol: "LTC",
    amount: 5,
    price: 150,
    tradeType: "buy",
    location: "San Francisco, USA",
    paymentMethod: "Venmo",
    timestamp: "2023-07-23T11:00:00Z",
  },
  {
    traderName: "David",
    symbol: "BTC",
    amount: 0.8,
    price: 46000,
    tradeType: "sell",
    location: "Toronto, Canada",
    paymentMethod: "Cash",
    timestamp: "2023-07-24T16:45:00Z",
  },
  {
    traderName: "Fiona",
    symbol: "ETH",
    amount: 1.5,
    price: 3200,
    tradeType: "buy",
    location: "Berlin, Germany",
    paymentMethod: "SEPA Transfer",
    timestamp: "2023-07-25T12:30:00Z",
  },
  {
    traderName: "George",
    symbol: "LTC",
    amount: 3,
    price: 140,
    tradeType: "sell",
    location: "Paris, France",
    paymentMethod: "PayPal",
    timestamp: "2023-07-26T09:15:00Z",
  },
  {
    traderName: "Hannah",
    symbol: "XRP",
    amount: 500,
    price: 2,
    tradeType: "buy",
    location: "Singapore",
    paymentMethod: "Bank Wire",
    timestamp: "2023-07-27T19:20:00Z",
  },
  {
    traderName: "Alice",
    symbol: "BTC",
    amount: 0.3,
    price: 47000,
    tradeType: "buy",
    location: "New York, USA",
    paymentMethod: "Zelle",
    timestamp: "2023-07-28T14:00:00Z",
  },
  // Additional 10 trading transactions
  {
    traderName: "Ethan",
    symbol: "ETH",
    amount: 0.7,
    price: 2900,
    tradeType: "sell",
    location: "Los Angeles, USA",
    paymentMethod: "Cash",
    timestamp: "2023-07-29T11:45:00Z",
  },
  {
    traderName: "Isabella",
    symbol: "BTC",
    amount: 0.6,
    price: 46000,
    tradeType: "buy",
    location: "Melbourne, Australia",
    paymentMethod: "Cryptocurrency Wallet",
    timestamp: "2023-07-30T08:30:00Z",
  },
  {
    traderName: "Jack",
    symbol: "XRP",
    amount: 800,
    price: 1.8,
    tradeType: "sell",
    location: "Vancouver, Canada",
    paymentMethod: "Bank Transfer",
    timestamp: "2023-07-31T17:30:00Z",
  },
  {
    traderName: "Olivia",
    symbol: "LTC",
    amount: 7,
    price: 160,
    tradeType: "buy",
    location: "Madrid, Spain",
    paymentMethod: "PayPal",
    timestamp: "2023-08-01T13:15:00Z",
  },
  {
    traderName: "James",
    symbol: "ETH",
    amount: 1.2,
    price: 3100,
    tradeType: "buy",
    location: "Paris, France",
    paymentMethod: "Credit Card",
    timestamp: "2023-08-02T10:00:00Z",
  },
  {
    traderName: "Sophia",
    symbol: "BTC",
    amount: 0.4,
    price: 47500,
    tradeType: "sell",
    location: "London, UK",
    paymentMethod: "Bank Wire",
    timestamp: "2023-08-03T15:45:00Z",
  },
  {
    traderName: "Noah",
    symbol: "LTC",
    amount: 4,
    price: 145,
    tradeType: "sell",
    location: "Toronto, Canada",
    paymentMethod: "Venmo",
    timestamp: "2023-08-04T12:20:00Z",
  },
  {
    traderName: "Ava",
    symbol: "XRP",
    amount: 600,
    price: 1.9,
    tradeType: "buy",
    location: "New York, USA",
    paymentMethod: "Zelle",
    timestamp: "2023-08-05T18:00:00Z",
  },
  {
    traderName: "William",
    symbol: "BTC",
    amount: 0.8,
    price: 48000,
    tradeType: "buy",
    location: "Sydney, Australia",
    paymentMethod: "Cryptocurrency Wallet",
    timestamp: "2023-08-06T16:30:00Z",
  },
  {
    traderName: "Mia",
    symbol: "ETH",
    amount: 1.8,
    price: 3050,
    tradeType: "sell",
    location: "Berlin, Germany",
    paymentMethod: "SEPA Transfer",
    timestamp: "2023-08-07T10:15:00Z",
  },
];
